-- Every attempt a model makes to enter, filled or not, with the decision-time ask
-- (snapshot_ask), the ask re-read just before the order (fresh_ask), the limit the
-- order would cross to (max_price), the notional available up to that limit, and
-- the lag between the two book reads. Used to measure fill rate and slippage.
create table if not exists public.entry_attempts (
  id bigint generated by default as identity primary key,
  prediction_id bigint not null references public.predictions(id),
  model text not null,
  mode text not null check (mode in ('paper', 'shadow', 'live')),
  side text check (side in ('up', 'down')),
  outcome text not null,
  snapshot_ask double precision,
  fresh_ask double precision,
  max_price double precision,
  depth_to_max_usd double precision,
  stake_usd double precision not null,
  fill_price double precision,
  lag_ms double precision,
  ts double precision not null,
  created_at timestamptz not null default now()
);

create index if not exists entry_attempts_model_ts_idx
  on public.entry_attempts(model, ts);

alter table public.entry_attempts enable row level security;

revoke all on table public.entry_attempts from public, anon, authenticated;
revoke all on sequence public.entry_attempts_id_seq from public, anon, authenticated;

comment on table public.entry_attempts is
  'PMJEV entry attempts (fill-rate telemetry). RLS enabled, no browser-facing policy.';
