create schema if not exists pmjev;

revoke all on schema pmjev from public, anon, authenticated;

create table pmjev.windows (
  slug text primary key,
  asset text not null,
  window_start bigint not null check (window_start > 0),
  up_token text,
  down_token text,
  condition_id text,
  price_to_beat double precision,
  close_price double precision,
  outcome smallint check (outcome in (0, 1)),
  status text not null check (status in ('open', 'no_open', 'resolved', 'error')),
  redeem_status text check (redeem_status in ('pending', 'redeemed', 'error')),
  redeem_tx text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table pmjev.predictions (
  id bigint generated by default as identity primary key,
  slug text not null references pmjev.windows(slug),
  t_elapsed integer not null check (t_elapsed > 0),
  ts double precision not null,
  spot_chainlink double precision not null,
  spot_binance double precision not null,
  sigma_1s double precision not null check (sigma_1s >= 0),
  up_bid double precision,
  up_ask double precision,
  down_bid double precision,
  down_ask double precision,
  depth_ask_usd double precision not null check (depth_ask_usd >= 0),
  p_jev double precision check (p_jev between 0 and 1),
  p_jev_mkt double precision check (p_jev_mkt between 0 and 1),
  p_gbm double precision not null check (p_gbm between 0 and 1),
  p_trend_gbm double precision check (p_trend_gbm between 0 and 1),
  jev_latency_ms double precision check (jev_latency_ms >= 0),
  jev_error text,
  state_json jsonb not null,
  created_at timestamptz not null default now(),
  constraint predictions_slug_checkpoint unique (slug, t_elapsed),
  constraint predictions_id_slug unique (id, slug)
);

create table pmjev.trades (
  id bigint generated by default as identity primary key,
  window_slug text not null,
  prediction_id bigint not null,
  model text not null check (model in ('gbm', 'trend_gbm', 'jev', 'jev_mkt')),
  mode text not null check (mode in ('paper', 'shadow', 'live')),
  side text not null check (side in ('up', 'down')),
  price double precision not null check (price >= 0 and price <= 1),
  size double precision not null check (size > 0),
  fee double precision not null check (fee >= 0),
  order_id text,
  fill_price double precision check (fill_price >= 0 and fill_price <= 1),
  pnl double precision,
  exit_price double precision check (exit_price >= 0 and exit_price <= 1),
  exit_fee double precision check (exit_fee >= 0),
  closed_at double precision,
  execution_status text not null default 'matched',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint trades_prediction_window_fk
    foreign key (prediction_id, window_slug)
    references pmjev.predictions(id, slug),
  constraint trades_window_model_unique unique (window_slug, model)
);

create index windows_status_start_idx
  on pmjev.windows(status, window_start);

create index predictions_ts_idx
  on pmjev.predictions(ts);

create index predictions_jev_attempts_idx
  on pmjev.predictions(ts)
  where jev_latency_ms is not null or jev_error is not null;

create index trades_open_mode_idx
  on pmjev.trades(mode, execution_status)
  where pnl is null;

create index trades_closed_mode_idx
  on pmjev.trades(mode, closed_at)
  where pnl is not null;

alter table pmjev.windows enable row level security;
alter table pmjev.predictions enable row level security;
alter table pmjev.trades enable row level security;

revoke all on all tables in schema pmjev from public, anon, authenticated;
revoke all on all sequences in schema pmjev from public, anon, authenticated;

comment on schema pmjev is
  'Private operational schema for the PMJEV worker. It is not exposed through the Data API.';
